# Generated by Django 5.1.2 on 2024-11-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='forget_token',
        ),
    ]
