# Generated by Django 5.1.2 on 2024-11-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0006_alter_siteinfo_support_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='support_mobile',
            new_name='support_phone_number',
        ),
    ]
