# Generated by Django 5.1.2 on 2024-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0007_rename_support_mobile_siteinfo_support_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='support_phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
