# Generated by Django 5.1.2 on 2024-11-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0008_alter_siteinfo_support_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
