# Generated by Django 5.1.2 on 2024-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0009_delete_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('support_email', models.EmailField(max_length=254)),
                ('support_phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
