# Generated by Django 5.1.2 on 2024-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0010_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='application',
            field=models.CharField(default='blog', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='status',
            field=models.CharField(default='salam', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='version',
            field=models.CharField(default='salam', max_length=30),
            preserve_default=False,
        ),
    ]
